[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wallet-mcp"
version = "0.1.0"
description = "MCP server with context manager, OpenAI, and Web3 adapters"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "Your Name"}]
dependencies = [
  "pydantic==2.5.0",
  "tiktoken==0.6.0",
  "openai==1.20.0",
  "web3==6.15.0",
  "eth-account==0.10.0",
  "cryptography==42.0.5",
  "structlog==23.2.0",
  "aiocache==0.12.11",
  "python-dotenv==1.0.0",
]

[project.optional-dependencies]
dev = [
  "pytest==7.4.3",
  "pytest-asyncio==0.23.7",
  "httpx==0.25.2",
]

[project.scripts]
wallet-mcp = "wallet_mcp_server:cli"

[tool.setuptools]
py-modules = ["wallet_mcp_server"]

